Pin the version of dill for attention_is_all_you_need_pytorch (#922)
Summary:
`attention_is_all_you_need_pytorch` requires dill == 0.3.4, newer dill version will have the following error:
```
ModuleNotFoundError: No module named 'dill._shims'
```

Fix another API change of `prepare_qat_fx` API (https://github.com/pytorch/pytorch/pull/77608)

Pull Request resolved: https://github.com/pytorch/benchmark/pull/922

Reviewed By: erichan1

Differential Revision: D36600030

Pulled By: xuzhao9

fbshipit-source-id: 8877476cc1d16f23c63af79016e44f6c5b69772e