add condition in enable_amp to fix eval not work under amp (#2228)
Summary:
when we running alexnet eval with amp, it will failed due to AttributeError: 'Model' object has no attribute 'forward_contexts'
when i check the code, i found that it will go into the is_staged_train_test and even i just want to run eval.
so i modify the condition and it will pass then.

Pull Request resolved: https://github.com/pytorch/benchmark/pull/2228

Reviewed By: aaronenyeshi

Differential Revision: D56219179

Pulled By: xuzhao9

fbshipit-source-id: 1b69a87fc10dcba427573ad47edf74edd9c8e5f3