torch_multimodal_clip model get failed due to network issue (#2289)
Summary:
Description:
while running model torch_multimodal_clip getting this issue
FileNotFoundError: [Errno 2] No such file or directory: 'torchbenchmark/models/torch_multimodal_clip/.data/pizza.jpg'
main reason is while downloading the pizza.jpg , getting Failed to download file with status code 403 issue so this change will resolve this issue

Pull Request resolved: https://github.com/pytorch/benchmark/pull/2289

Reviewed By: aaronenyeshi

Differential Revision: D58813450

Pulled By: xuzhao9

fbshipit-source-id: aa4cbee8fa4633182898fe7c1037b471505ce2ec