Fix a bug
Summary:
When testing with:
  buck2 run mode/opt //pytorch/benchmark:run -- mimo_cmf_30x -d cuda -t train --torchdynamo inductor --profile --shrink_model True --bs 10 --profile-detailed

 {F1104965994}
It failed with AttributeError: 'NoneType' object has no attribute 'num_batch'. This is because `model` is not passed into `printResultSummaryTime` in `profile_one_step`.

In this diff, we pass `model` to `printResultSummaryTime` in `profile_one_step`.

Reviewed By: xuzhao9

Differential Revision: D49749228

fbshipit-source-id: d22f652723354966af6da68cd0bd48f2abfe637a