Add torchtext to fix benchmark installation error
TorchText is missing in the command,
conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch-nightly -c nvidia
resulting in the following installation error:
$ python install.py
checking packages torch, torchvision, torchtext, torchaudio are installed...FAIL
Error: Users must first manually install packages
['torch', 'torchvision', 'torchtext', 'torchaudio'] before installing the benchmark.