fix bug for opt_args.use_cosine_similarity (#1115)
Summary:
The previous PR https://github.com/pytorch/benchmark/pull/1110 introduced a bug when I use torchdynamo.

```bash
AttributeError: 'Namespace' object has no attribute 'use_cosine_similarity'
```

Pull Request resolved: https://github.com/pytorch/benchmark/pull/1115

Reviewed By: xuzhao9

Differential Revision: D38758681

Pulled By: FindHao

fbshipit-source-id: c61ea6fb394d4f80f5e1a9c7490f35a5e099d534