NotImplementedError: Model's DEFAULT_TRAIN_BSIZE is not implemented. (#2563)
Summary:
Some tests fail in train mode. I found missing fields in specific models and added DEFAULT_TRAIN_BSIZE with the same value as eval batch size.

Pull Request resolved: https://github.com/pytorch/benchmark/pull/2563

Reviewed By: adamomainz

Differential Revision: D69786156

Pulled By: xuzhao9

fbshipit-source-id: aedf72d758d31e59f3c9b611d1ae0a46fee7c7f4