Added missing batch.pt file for functorch_maml_omniglot (#2145)
Summary:
`functorch_maml_omniglot` [tries to load some inputs ](https://github.com/pytorch/benchmark/blob/main/torchbenchmark/models/functorch_maml_omniglot/__init__.py#L73) from a file that it has not downloaded in its `install.py`. This should be done similarly to [how it's done for maml_omniglot](https://github.com/pytorch/benchmark/blob/main/torchbenchmark/models/maml_omniglot/install.py).

Testing before:

```
FileNotFoundError: [Errno 2] No such file or directory: 'benchmark/torchbenchmark/models/maml_omniglot/batch.pt'

(...)

benchmark/components/_impl/workers/subprocess_rpc.py:458: FileNotFoundError
========================================================================= short test summary info ==========================================================================
FAILED benchmark/test.py::TestBenchmark::test_functorch_maml_omniglot_check_device_cpu - FileNotFoundError: [Errno 2] No such file or directory
FAILED benchmark/test.py::TestBenchmark::test_functorch_maml_omniglot_eval_cpu - FileNotFoundError: [Errno 2] No such file or directory
FAILED benchmark/test.py::TestBenchmark::test_functorch_maml_omniglot_example_cpu - FileNotFoundError: [Errno 2] No such file or directory
FAILED benchmark/test.py::TestBenchmark::test_functorch_maml_omniglot_train_cpu - FileNotFoundError: [Errno 2] No such file or directory
```

and afterwards:

```
==================================================================== 4 passed, 384 deselected in 12.55s ====================================================================
```

Pull Request resolved: https://github.com/pytorch/benchmark/pull/2145

Reviewed By: aaronenyeshi

Differential Revision: D53316976

Pulled By: xuzhao9

fbshipit-source-id: c695054723a902280823d66e2e6a727f9cc934ca