README.md fix (#1316)
Summary:
The torchaudio is missing when create new env and install.

Error message:
checking packages torch, torchvision, torchtext, torchaudio are installed...FAIL
Error: Users must first manually install packages ['torch', 'torchvision', 'torchtext', 'torchaudio'] before installing the benchmark.

Pull Request resolved: https://github.com/pytorch/benchmark/pull/1316

Reviewed By: FindHao

Differential Revision: D41426191

Pulled By: xuzhao9

fbshipit-source-id: 3112de180d656a804dc4d8f39e8ae4975da26917